[2021-12-10 13:19:47,541] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: core_concepts.python_function 2021-12-10T18:17:59.310340+00:00 [queued]>
[2021-12-10 13:19:47,547] {taskinstance.py:669} INFO - Dependencies all met for <TaskInstance: core_concepts.python_function 2021-12-10T18:17:59.310340+00:00 [queued]>
[2021-12-10 13:19:47,547] {taskinstance.py:879} INFO - 
--------------------------------------------------------------------------------
[2021-12-10 13:19:47,547] {taskinstance.py:880} INFO - Starting attempt 1 of 1
[2021-12-10 13:19:47,547] {taskinstance.py:881} INFO - 
--------------------------------------------------------------------------------
[2021-12-10 13:19:47,550] {taskinstance.py:900} INFO - Executing <Task(PythonOperator): python_function> on 2021-12-10T18:17:59.310340+00:00
[2021-12-10 13:19:47,554] {standard_task_runner.py:53} INFO - Started process 2855 to run task
[2021-12-10 13:19:47,584] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: core_concepts.python_function 2021-12-10T18:17:59.310340+00:00 [running]> 220.1.168.192.in-addr.arpa
[2021-12-10 13:19:47,593] {logging_mixin.py:112} INFO - 0.13436424411240122
[2021-12-10 13:19:47,594] {python_operator.py:114} INFO - Done. Returned value was: None
[2021-12-10 13:19:47,597] {taskinstance.py:1065} INFO - Marking task as SUCCESS.dag_id=core_concepts, task_id=python_function, execution_date=20211210T181759, start_date=20211210T181947, end_date=20211210T181947
[2021-12-10 13:19:57,532] {logging_mixin.py:112} INFO - [2021-12-10 13:19:57,530] {local_task_job.py:103} INFO - Task exited with return code 0
